### ISSUE TITLE
移动端无法滚动

### ISSUE THREAD

**Issue by Clloz** [any86/any-touch#100]
使用 preventDefault: false 可以让移动端滚动，不过移动端 tap 需要长按（0.5s左右）才能触发，换成 click 正常，并且 pan 会触发滚动条的滚动。
如果去掉 preventDefault：false tap 正常，不过移动端没饭滚动，click 也无效，换成 tap 以后正常。

我想问一下有没有什么比较好的办法能够在不使用 preventDefault: false 的情况下让滚动条能够正常滚动。我现在是在 pan 事件里面修改 scrollTop，不过这样滚动没有加速度，很不流畅。

代码就差不多下面这个形式，左侧的滚动条在移动端下无法滚动（在不使用 preventDefault: false 的情况下）。

![Screen-Recording-2022-05-15-at-21 31 55](https://user-images.githubusercontent.com/17775199/168475662-3e34a1d6-9dea-4c99-b021-9fcfa0cb8300.gif)

``` vue
<script lang="ts" setup>
const el = document.getElementById('point-list')
const at = new AnyTouch(el)

onMounted(() => {
  at.on('pan', (e) => {
    
  })
  
  at.on('panend', (e) => {
    
  })
})
</script>
<div id="point-list" class="list">
    <div class="item" v-for="(point, index) in pointList" :key="index" @tap="toggleSelection(index)">{{point.name}}</div>
</div>
```

**Comment by any86** [comment]
兄弟你上面描述的第二段好像有打错字的地方, 所以我没太看懂你的需求, 你先说下你需要用到哪几个手势, 我帮你分析下怎么弄

**Comment by any86** [comment]
preventDefault实际他的值可以是[函数](https://github.com/any86/any-touch/blob/master/docs/advanced.CN.md#%E9%98%BB%E6%AD%A2%E9%BB%98%E8%AE%A4%E4%BA%8B%E4%BB%B6), 函数的参数是当前元素的事件对象, 所以可以根据元素上的属性来决定是否"阻止浏览器默认行为"

不知道这点能否解决你的问题, 不行咱俩再研究

**Comment by Clloz** [comment]
我其实就一个固定高度的盒子里面有加载一些 item，就像上面图里面的 a301 a302 这样的，然后我要把选中的拖动（其实就是做个效果）。我就是在盒子上绑定的 pan 事件，拖动的时候有个半透明的 div 显示拖动效果这样，拖到右边的区域就把选中的 item 放到右边这样。
然后现在我是盒子作为 anytouch 的绑定元素，盒子我是设置的overflow: auto，但是在移动端无法滚动

**Comment by Clloz** [comment]
然后这些 item 我现在用的是 tap 来进行选中的，在不使用 preventDefault 的时候 click 在移动端是不生效，我也看过之前的 issue，现在换成 tap 能正常工作。但是如果用 preventDefault: false 的话 tap 好像就要按住大概 0.5s 才能生效。

**Comment by Clloz** [comment]
> preventDefault实际他的值可以是[函数](https://github.com/any86/any-touch/blob/master/docs/advanced.CN.md#%E9%98%BB%E6%AD%A2%E9%BB%98%E8%AE%A4%E4%BA%8B%E4%BB%B6), 函数的参数是当前元素的事件对象, 所以可以根据元素上的属性来决定是否"阻止浏览器默认行为"
> 
> 不知道这点能否解决你的问题, 不行咱俩再研究

好的，我试试，谢谢你这么快回复我。

**Comment by any86** [comment]
客气啦. tap并没有延迟啊,  你是开启"双击"了吗? 你现在用的any-touch的版本是多少?

**Comment by Clloz** [comment]
我用的版本是 2.1.2，我是开了 preventDefault: false 在移动端需要长按（就是如果像click一样就点一下，就没效果），开了以后 click 就可以正常用，我试试看截图能不能看出来。

**Comment by Clloz** [comment]
确实是双击的问题，事件触发了两次

**Comment by Clloz** [comment]
不过我也没特别开启双击，这个需要手动关闭么

**Comment by any86** [comment]
话说回逻辑吧, 我明白了你的需求. 但是既然想要拖拽, 那么就没办法不组织滚动,  因为浏览器也不知道你是要拖拽物体还是要滚动列表, 所以这里建议在UI上改一下, 比如:
给列表的内边距增大, 同时通过preventDefault函数来保证只有拖拽item的时候阻止默认, 这样其他地方的拖拽就会产生滚动.

**Comment by any86** [comment]
应该不是绑定的问题, 我demo里也是这么写的, 有机会你弄个的在线的demo, 我现在没复现出来.

> 我打印了好像是只加载了默认的六种手势，是不是我的 tap 绑定有什么问题，我就是在盒子内的 v-for 上面给每个元素绑定的 tap。我也是第一次做这种手势相关的，谢谢你的这个开源库还有建议，我后面去改一改。

**Comment by Clloz** [comment]
好的，我今天晚上弄个在线 demo，到时候发你看一下

**Comment by any86** [comment]
已修复, 还没写用例, 暂不发版
