### ISSUE TITLE
【BUG】Vue3 中指令方式设置参数没效果

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#101]
![image](https://user-images.githubusercontent.com/16074662/170441477-67805cfa-8683-41cd-8ecb-f76726048e7e.png)
tapTimes 设置了 3，但点击 1 次还是触发了 tap

**Comment by any86** [comment]
误会了, 指令的值是AnyTouch构造函数的参数, 指令我只是做了个小样, 具体没想好都需要暴露什么,  你可以提点建议, 我想下怎么满足, 不过的重新发版.

**Comment by 1014156094** [comment]
好吧
