### ISSUE TITLE
【BUG】Vue3 press 按压事件不触发

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#102]
![image](https://user-images.githubusercontent.com/16074662/170445061-f53e4822-0ccb-4043-8097-6edd73e5f351.png)
![image](https://user-images.githubusercontent.com/16074662/170445082-73d4a224-0d65-41c6-8bb3-2389dc44fbfc.png)
![image](https://user-images.githubusercontent.com/16074662/170445561-03694f3c-b099-488d-b2b3-78bdcb79a190.png)

**Comment by any86** [comment]
用的Core吗? 加载press了吗?

**Comment by 1014156094** [comment]
> 用的Core吗? 加载press了吗?

对
import Core from '@any-touch/core'
import press from '@any-touch/press'

**Comment by any86** [comment]
好的, 现在比较忙, 稍后测一下 , 最后给我一个在线的复现.

**Comment by any86** [comment]
你之前不是一直在用吗? 是2.2.0版本才有这个问题?

**Comment by 1014156094** [comment]
> 2.2.0版本

2.2.0版本，建议作者不要维护vue2了，问题有点多，不维护vue2的话精力多点

**Comment by any86** [comment]
你冤枉vue2了... 有问题也是我插件的问题.  

我试了下, 并没有问题啊, 你看看模拟下你的代码: https://codesandbox.io/s/heuristic-rui-zymb8l?file=/src/App.vue
