### ISSUE TITLE
@any-touch/pan 怎么动态设置 pointLength 呢

### ISSUE THREAD

**Issue by hellohejinyu** [any86/any-touch#108]
使用场景是画笔在画布上画画，画笔未激活时用户可以用单指移动画布，但是画笔激活时，单指移动就是画画了。此时双指移动才是移动画布。

**Comment by any86** [comment]
定义一个双指拖拽识别器: 
```typescript
// 只加载pan识别器(拖拽)
import ATouch from 'any-touch';
import pan from '@any-touch/pan';

const at = new ATouch (el);
at.use(pan, {pointLength :2, name:'pan2'})

// 单指拖拽
at.on('pan', (event) => {
   
});

// 双指拖拽 
at.on('pan2', (event) => {
    
});
```

**Comment by hellohejinyu** [comment]
> 定义一个双指拖拽识别器:
> 
> ```ts
> // 只加载pan识别器(拖拽)
> import ATouch from 'any-touch';
> import pan from '@any-touch/pan';
> 
> const at = new ATouch (el);
> at.use(pan, {pointLength :2, name:'pan2'})
> 
> // 单指拖拽
> at.on('pan', (event) => {
>    
> });
> 
> // 双指拖拽 
> at.on('pan2', (event) => {
>     
> });
> ```

赞，原来 name 字段是用来干这个的。我以为一种手势只能被 use 一次。
