### ISSUE TITLE
父元素监听 panmove, pinch 事件，子元素中 mousedown 不再触发

### ISSUE THREAD

**Issue by wenwuwu** [any86/any-touch#111]
非常感谢实现这样一个手势库，总体很棒。

目前主要有一个问题，如题所述，在 parentElement 如果监听 panmove, pinch 事件，childElement 里 mousedown 事件不再触发。我将 panmove, pinch 移动到内层元素，mousedown 又可以了。但是我需要在 window.document.body 层面处理panmove & pinch，结果所有元素的 mousedown 监听函数都不再触发。（项目是 PC 和移动端共用代码）

不确定哪里出了问题。

**Comment by wenwuwu** [comment]
抱歉，仔细看了下文档。{ preventDefault: false } 可以解决问题。

**Comment by any86** [comment]
我研究下, 可以发部

> 抱歉，仔细看了下文档。{ preventDefault: false } 可以解决问题。

刚才在忙单位的事情, 寻思一会帮你看下呢.哈哈.
