### ISSUE TITLE
如何在uniapp 中使用？

### ISSUE THREAD

**Issue by yun3948** [any86/any-touch#116]
你好，不知道这个插件能不能在uniapp 中使用，可以的话，应该如何操作？按照小程序的代码好像有问题，我对前端不是特别了解，有空的话麻烦解答一下，感谢

**Comment by any86** [comment]
uniapp我没有用过, 工作中接触不到, any-touch主要是针对web.

**Comment by yun3948** [comment]
好的，我这边研究一下，谢谢
