### ISSUE TITLE
有关 changelog

### ISSUE THREAD

**Issue by dev-itsheng** [any86/any-touch#121]
请问一下作者，现在从 1.0.12 能否直接升级到 2.2.0，有没有 break change。

项目根目录下的 CHANGELOG.md 已经看过了，内容不全……

**Comment by any86** [comment]
不好意思啊, 时间太久了, 细节记不住了, 但是大体是没变的, 比如`on`绑定事件和事件名都没变, 2.0开始主要是做了代码拆分的改变, 双击手势的创建变了, 但是我已经直接做成包了, 可以直接用:
https://github.com/any86/any-touch/tree/master/packages/doubletap

### preventDefault参数
增加了函数的用法:
https://github.com/any86/any-touch/blob/master/docs/advanced.CN.md#%E9%98%BB%E6%AD%A2%E9%BB%98%E8%AE%A4%E4%BA%8B%E4%BB%B6

印象里如果不是要自己创建新的手势, 那么没变化
