### ISSUE TITLE
vue   报这个错误是什么原因导致的？

### ISSUE THREAD

**Issue by Mariah-feifei** [any86/any-touch#20]
[]([](![image](https://user-images.githubusercontent.com/30531971/83111743-a1caa500-a0f7-11ea-883c-b616442ae7e5.png)))

![image](https://user-images.githubusercontent.com/30531971/83111627-7d6ec880-a0f7-11ea-89b6-db3f4a1fdbac.png)

**Comment by Mariah-feifei** [comment]
![image](https://user-images.githubusercontent.com/30531971/83111827-bf980a00-a0f7-11ea-9af6-8878b7c069fd.png)

**Comment by any86** [comment]
你输出下`this.$refs.pdfs`, 看看他是不是一个dom元素, 因为any-touch内部会执行:
```javascript
this.$refs.pdfs.style.webkitTapHighlightColor = 'rgba(0,0,0,0)';
```

**Comment by Mariah-feifei** [comment]
啊！！是的，取到的是个数组  现在可以了   谢啦
