### ISSUE TITLE
发现一个小问题

### ISSUE THREAD

**Issue by Real102** [any86/any-touch#28]
在pc端直接查看demo时，鼠标 “swipe（滑动）” 操作时，若是往右滑动，会出现滚动条；但若 “用力” 往左滑动时，会导致容器div滑到窗口以外的地方，并且不会产生滚动条，变得 “消失了”

![1](https://user-images.githubusercontent.com/24390756/90729742-9acbc100-e2f9-11ea-979e-1f9c0244bd7c.png)

**Comment by any86** [comment]
感谢反馈, 这个demo做的比较草, 稍后我优化

**Comment by zhaoyunchong** [comment]
大佬你的介绍文档中 document 拼错了

**Comment by any86** [comment]
之前改完了, 感谢 @zhaoyunchong
