### ISSUE TITLE
问一个关于两指doubleclick的问题，我这个没有生效

### ISSUE THREAD

**Issue by PoisonSnowFlying** [any86/any-touch#31]
Core.use(Tap,{name:'twoFingersTap',tapTimes:2,pointLength:2});
const at = new Core(targetDOM);
  at.on('twoFingersTap', (ev) => {
            console.log(ev)
            // ev包含位置/速度/方向等信息
        });

**Comment by PoisonSnowFlying** [comment]
两个手指的两次点击操作。
我也在别的事件上设置了pointLength属性，但是都没有生效。我不知道目前这个参数是否支持

**Comment by any86** [comment]
支持, 我自己模拟了下, 应该是2手指Tap的时候, 产生的距离太大了, 超过了选项里的maxDistanceFromPrevTap(默认9), 

这个值的意思就是每次点击允许发生的最大距离.

所以, 你可以修改这个值: 
```
AnyTouch.use(Tap, { name: 'twoFingersTap', tapTimes: 2, pointLength: 2,maxDistanceFromPrevTap:30 });

```

**Comment by any86** [comment]
这已经添加了这个测试用例, 所以可以确定"twoFingersTap"以及"多支多击"是好使的.

**Comment by any86** [comment]
我实际按照我的手指maxDistanceFromPrevTap = 100还可以, 这个值也没啥建议值, 自己找一个合适的值吧, 我用的100可以

**Comment by PoisonSnowFlying** [comment]
嗯嗯，看到了你的test，但是实际在例子中跑的时候没生效，直接就是页面给放大了(mac双指double点击)。自身绑定的事件没生效

**Comment by any86** [comment]
mac双指和手机上的双指不是一个事件, mac的双指默认对应鼠标滑动动作.

最好用真实手机测试, 如果没记错mac的3指对应的才是手机上的1指.
