### ISSUE TITLE
能否只允许单一方向拖拽？

### ISSUE THREAD

**Issue by overofheight** [any86/any-touch#32]
有没有只允许横向或竖向拖拽的属性配置；还有就是没有找到停止拖拽的函数或方法

**Comment by any86** [comment]
横/竖暂时可以通过判断e.direction === 'left'或者'right'来实. 不知道你可不可以满足你的需求, 如有问题你和我描述下你的需求, 暂时不想在配置中加方向的限制, 之前加过, 后来觉得功能很少用给取消了.


停止试一下:
```javascript
const pan = at.get('pan');
if (void 0 !== pan) {
    pan.set({ disabled: true });
}
```

**Comment by any86** [comment]
停止其实早期也加过一个api叫stop, 也是觉得小众, 考虑体积给删了, 如过不满足说下需求再研究

**Comment by any86** [comment]
对识别器的控制, 为了灵活我建议都通过[beforeEach](https://github.com/any86/any-touch/blob/master/docs/API.md#beforeeachhook)来控制
