### ISSUE TITLE
panend不触发

### ISSUE THREAD

**Issue by FourLeafTec** [any86/any-touch#33]
version:1.0.5
浏览器:Chrome 86.0.4240.75
操作系统:macOS

panend不触发,并且会在临近结束随机触发一个或多个pannone
![截屏2020-10-12 下午1 16 48](https://user-images.githubusercontent.com/5875432/95708219-49eb9f80-0c8e-11eb-8c4d-3684c7741fbd.png)

另外请问下,演示中的版本是哪个版本啊? 演示版本没这个问题,我用的功能都没问题,项目有点急

**Comment by any86** [comment]
好的我检查下， 有问题稍等我修复， panone是指什么？

**Comment by FourLeafTec** [comment]
不太清楚,可以看到在我机器上运行的演示程序里出来的type就叫pannone
另外低版本依赖貌似有点问题,我想用1.0.4或者更低来找一下github.io上那个演示程序用的版本,
结果npm安装出来@any-touch/core等实际库的版本都是1.0.5
![截屏2020-10-12 下午1 46 59](https://user-images.githubusercontent.com/5875432/95709556-6fc67380-0c91-11eb-9ef0-745dec3569a0.png)

**Comment by any86** [comment]
我大概知道什么原因，你着急可以先用0.7.9版本， 一会1.0.6我解决后发布，稍后直接更近即可，新版本只是beforeEach那个api有变化， 暂时放心用0.7.9

**Comment by FourLeafTec** [comment]
Ok 0.7.9可以解决我的问题

**Comment by any86** [comment]
v1.0.6已修复
