### ISSUE TITLE
求助一个事情

### ISSUE THREAD

**Issue by SKHon** [any86/any-touch#34]
作者您好，我现在有个急需求，需要参考一下官方的这个实现。可以给我发一下这个demo的代码吗？
![image](https://user-images.githubusercontent.com/4202352/103723284-b0255b80-500c-11eb-8264-25ec43c9f431.png)

**Comment by any86** [comment]
https://github.com/any86/any-touch/tree/master/example
代码都在这里😂

**Comment by SKHon** [comment]
非常感谢，救命了
