### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#37]
![image](https://user-images.githubusercontent.com/16074662/105460115-44a6e380-5cc6-11eb-8549-00bf13e281d0.png)
![image](https://user-images.githubusercontent.com/16074662/105460221-6c964700-5cc6-11eb-98b0-b4746ae891fb.png)

没有 `this.on`，只有 `this.$on` 或 `this.$once`

**Comment by any86** [comment]
笔误, 感谢已修复
