### ISSUE TITLE
文档没有说明 pan 事件怎么判断是否已结束

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#38]
pan 事件怎么区分 start move end 呢？文档没说明噢~

**Comment by any86** [comment]
好的, 我稍后追加文档

**Comment by any86** [comment]
补充下: 有panstart panmove panend 3个事件表示拖拽的3个阶段

**Comment by 1014156094** [comment]
好的

**Comment by any86** [comment]
已更新
[还支持哪些手势?](https://github.com/any86/any-touch#%E8%BF%98%E6%94%AF%E6%8C%81%E5%93%AA%E4%BA%9B%E6%89%8B%E5%8A%BF)
