### ISSUE TITLE
使用 any-touch 后，Vue 的 @click 事件在移动端失效

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#39]

**Comment by any86** [comment]
请提供下代码, 我复现下

**Comment by 1014156094** [comment]
![image](https://user-images.githubusercontent.com/16074662/105653536-080dfe80-5ef7-11eb-8534-bcba4df190af.png)

**Comment by 1014156094** [comment]
如上图，代码很简单，能懂，我就不发源码了

**Comment by 1014156094** [comment]
有临时解决方案么？

**Comment by any86** [comment]
上午开会去了, 我检查了并没有这个问题啊

**Comment by any86** [comment]
https://codepen.io/russell2015/pen/jOMgOVj

**Comment by any86** [comment]
移动端下确实有问题, 我检查下, 你先用tap代替click吧

**Comment by any86** [comment]
`preventDefault:false`会造成pan触发的时候, 整体浏览器滚动条也会滑动, 建议放弃click用anytouch的tap代替

**Comment by any86** [comment]
在移动端touchstart比click先触发, anytouch在移动端都是基于touch事件模拟的其他事件, 所以touchstart阶段的`preventDefault`会阻止click触发: https://codepen.io/russell2015/pen/jOMgOVj
