### ISSUE TITLE
缩放一直识别成两个触点

### ISSUE THREAD

**Issue by Iamisheshuai** [any86/any-touch#5]
完成一次缩放后，以后使用一个手指都会被识别成两个触点。

**Comment by any86** [comment]
好的, 我看下, 谢谢指正 🚀

**Comment by any86** [comment]
并没有啊? 请问是这个例子吗?
https://any86.github.io/any-touch/example/
能具体说下操作步骤吗?

**Comment by Iamisheshuai** [comment]
这个是我使用的代码。我第一次一只手指滑动没反应，只要我有了一次缩放行为后，用一只手指滑动都会触发缩放事件。
，麻烦您了。






------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 下午2:07
收件人: "any86/any-touch"<any-touch@noreply.github.com>; 
抄送: "1178189341"<1178189341@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [any86/any-touch] 缩放一直识别成两个触点 (#5)




并没有啊? 请问是这个例子吗?
 https://any86.github.io/any-touch/example/
 能具体说下操作步骤吗?

**Comment by any86** [comment]
那你把你的代码发一下吧 不然我很难复现哦.

**Comment by Iamisheshuai** [comment]
您好，这个是源码。




------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 下午2:07
收件人: "any86/any-touch"<any-touch@noreply.github.com>;
抄送: "1178189341"<1178189341@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [any86/any-touch] 缩放一直识别成两个触点 (#5)




并没有啊? 请问是这个例子吗?
 https://any86.github.io/any-touch/example/
 能具体说下操作步骤吗?

**Comment by any86** [comment]
为啥我看不到你说的源码...

**Comment by Iamisheshuai** [comment]
不是在附件中




------------------ 原始邮件 ------------------
发件人: "any86"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 下午2:20
收件人: "any86/any-touch"<any-touch@noreply.github.com>; 
抄送: "1178189341"<1178189341@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [any86/any-touch] 缩放一直识别成两个触点 (#5)




为啥我看不到你说的源码...

**Comment by Iamisheshuai** [comment]
我是用邮件发的。。。

**Comment by Iamisheshuai** [comment]
哥。要不我加你qq，这个用着太痛苦了

**Comment by any86** [comment]
383514580

**Comment by any86** [comment]
稍后我会在文档中标记这一点, 规避一下即可
