### ISSUE TITLE
pan事件中没有返回起始的点 

### ISSUE THREAD

**Issue by zwfun** [any86/any-touch#54]
at.on('panstart') 中返回的point并不是起始点，因为这时候distance已经是10了。 能不能返回startPoint

**Comment by any86** [comment]
可也试试把pan的`threshold`设置成0, 然后自己pan的钩子中自己增加`threshold`的逻辑, 比如:

```
at.on('pan', ({distance}=>{
    if(distance>threshold){
        // code
    }
}}
``
