### ISSUE TITLE
panend在移动端不触发

### ISSUE THREAD

**Issue by xiashui1994** [any86/any-touch#67]
panend在桌面端可以正常触发，但是在h5中无法触发

**Comment by any86** [comment]
网站的demo也不可以出发panend吗? 什么设备?
https://any86.github.io/any-touch/
请贴下代码

**Comment by xiashui1994** [comment]
网站的demo可以
设备：mac chrome
const at = new AnyTouch(el); 
at.set({ preventDefault: false });
at.on('panend', e => {
   console.log('e);
})
...

这样使用不可以？

**Comment by any86** [comment]
mac上的touchend出发有些延迟, 我暂时没带笔记本, 所以你可以按照实际手机测试, 之前我就发现mac上有写奇怪的行为, 稍后我回家测试下你的问题

https://github.com/any86/any-touch#macos%E4%B8%8A%E7%9A%84chrome%E6%B5%8F%E8%A7%88%E5%99%A8%E8%A7%A6%E5%8F%91touchend%E4%BC%9A%E6%AF%94%E8%BE%83%E6%85%A2

**Comment by xiashui1994** [comment]
感谢，也可能是xgplayer的原因
我在写一个xgplayer播放器的扩展插件，让xgplayer在手机上支持快进、快退调整音量等功能，有可能是xgplayer的功能影响到了

**Comment by xiashui1994** [comment]
确实是在xgplayer播放器播放视频之前panend都是正常的

**Comment by xiashui1994** [comment]
感谢您的回复，问题已经解决了，在xgplayer播放器中设置closeVideoStopPropagation: true 关闭点击播放器video元素的阻止冒泡行为就正常了

**Comment by any86** [comment]
感谢反馈, 我稍后研究暴露个冒泡相关的参数或者检测
