### ISSUE TITLE
跟原生事件有冲突

### ISSUE THREAD

**Issue by kailong321200875** [any86/any-touch#69]
因为插件默认阻止了原生事件，导致滚动条无法滚动，但是设置为true，就感觉很卡顿。跟原生事件冲突了。

**Comment by any86** [comment]
你的预期是2指触发pinch同时阻止默认事件, 1指正常拖动原生滚动?

**Comment by kailong321200875** [comment]
> 突然想起, 你可以通过这个api试试, 我上面说的逻辑. 我下班以后试下可行就会发到文档中 https://github.com/any86/any-touch/blob/master/docs/API.md
> 
> ![image](https://user-images.githubusercontent.com/8264787/138042277-6a9f1482-a240-4d2f-a235-7b8dead497cb.png)

我试试这个api

**Comment by any86** [comment]
我试了下, 可以这么写:
```javascript
        const at = new AnyTouch(this.$refs.panel, {
            preventDefault: true,
            preventDefaultExclude(e) {
                return 1 == e.touches.length;
            },
        });
```

**Comment by kailong321200875** [comment]
> 我试了下, 可以这么写:
> 
> ```js
>         const at = new AnyTouch(this.$refs.panel, {
>             preventDefault: true,
>             preventDefaultExclude(e) {
>                 return 1 == e.touches.length;
>             },
>         });
> ```
> 
> 只有>1指的时候才触发"阻止默认"

好的。
