### ISSUE TITLE
vue指令方式使用doubletap默认是false？

### ISSUE THREAD

**Issue by mysea** [any86/any-touch#7]
在以vue指令方式使用doubletap的时候，发现没效果，然后用了下面代码才可以，问题是，不应该默认是true吗？
`importAT (at) {
      const doubletap = at.get('doubletap')
      doubletap.disabled = false
    }`

**Comment by any86** [comment]
感谢反馈🚀

**默认是false, 这个是有意的.**

因为"双击"的识别需要让"单击"等待他的"第二下单击", 如果没有"第二下单击"那么"单击"触发, 否则识别为"双击"

基于上面的逻辑, 如果默认开启了"双击", 那么没有"双击"需求的人用的时候就会觉得"单击"反应慢(因为再等双击), 我看下是不是我文档没有写这个说明, 我一会补充上

**Comment by any86** [comment]
已在文档上说明

![image](https://user-images.githubusercontent.com/8264787/69596731-8f838780-103e-11ea-9e39-bbcb42d58852.png)

**Comment by mysea** [comment]
> 感谢反馈🚀
> 
> **默认是false, 这个是有意的.**
> 
> 因为"**双击**"的识别需要让"**单击**"等待他的"**第二下单击**", 如果没有"**第二下单击**"那么"**单击**"触发, 否则识别为"**双击**"
> 
> 基于上面的逻辑, 如果默认开启了"**双击**", 那么没有"**双击**"需求的人用的时候就会觉得"**单击**"反应慢(因为再等双击), **我看下是不是我文档没有写这个说明, 我一会补充上**

这个我知道，因为移动端是没有“双击”概念的，所谓的“双击”，就是两次间隔时间较短的“单击”，但是刚才在手机上试了，并不是每次双击都会有预期效果，目前不清楚是我点击区域设置不够大还是两次单击间隔时间的问题(比如默认间隔是300ms，实际上可能有时候是500ms，有时候是300ms)

**Comment by any86** [comment]
**300ms** 这个可以改, API文档再这里, https://github.com/any86/any-touch/blob/master/docs/API.md

![image](https://user-images.githubusercontent.com/8264787/69597090-c1491e00-103f-11ea-88b3-1f64849dda19.png)
