### ISSUE TITLE
绑定 Swipe 事件的元素中包含可滚动元素，则内部元素无法滚动。

### ISSUE THREAD

**Issue by hellohejinyu** [any86/any-touch#78]
![image](https://user-images.githubusercontent.com/8766034/145927459-a4a5a386-3af1-45e4-989d-19e9dd93b085.png)
红框内是一个浮动面板，在手机上通过监听 `swipeup` 和 `swipedown` 来显示和收回。面板中的绿色区域是一个长列表，在电脑上通过鼠标滚动可以正常滚动，但是在手机上通过手指上下划动就滚动不了了。

**Comment by any86** [comment]
这里说的滚动是系统滚动条的滚动吗?

**Comment by hellohejinyu** [comment]
> 这里说的滚动是系统滚动条的滚动吗?

是的。（你响应速度好快呀👍，我来搞个最小复现 demo 吧，方便你来解决：）

**Comment by any86** [comment]
好的, 感谢支持

**Comment by hellohejinyu** [comment]
> 好的, 感谢支持

https://codesandbox.io/s/wizardly-bas-jriqv?file=/src/App.js

可以了，在电脑上用鼠标是可以正常滚动的，但是在手机上就不行了。感谢你写的这个手势库，非常好用。

**Comment by any86** [comment]
午休了, 我一会回来研究下, 然后@你

**Comment by any86** [comment]
可以通过关闭"阻止默认事件"来让滚动条滚动
```javascript
const at = new Core(divRef.current, { preventDefault: false });
```
问题是未发生"swipe"之前拖拽页面, 页面会滚动不知道是不是你的预期?

我能想到的交互优化是在上下边缘放2个div(透明)用来触发swipe, 同时preventDefault: false, 这样能满足预期?

**Comment by any86** [comment]
我请教你个问题, 在react中是不可以绑定自定义dom事件吗?
```
    <div
      ref={divRef}
      onSwipeup={setVisible(true)}
      className={cn("panel", { show: visible })}
    >
```
会提示没有"onSwipeup"

**Comment by hellohejinyu** [comment]
> 可以通过关闭"阻止默认事件"来让滚动条滚动
> 
> ```js
> const at = new Core(divRef.current, { preventDefault: false });
> ```
> 
> 问题是未发生"swipe"之前拖拽页面, 页面会滚动不知道是不是你的预期?
> 
> 我能想到的交互优化是在上下边缘放2个div(透明)用来触发swipe, 同时preventDefault: false, 这样其他部分可以用来滚动页面, 这样能满足预期?

我试了一下，还是决定优化一下交互，感谢及时帮我解决问题🙏

**Comment by hellohejinyu** [comment]
> 我请教你个问题, 在react中是不可以绑定自定义dom事件吗?
> 
> ```
>     <div
>       ref={divRef}
>       onSwipeup={setVisible(true)}
>       className={cn("panel", { show: visible })}
>     >
> ```
> 
> 会提示没有"onSwipeup"

对的，不支持在 JSX 标签中直接写的，需要拿到 dom 然后用 JS 手动去绑。

**Comment by any86** [comment]
> > 我请教你个问题, 在react中是不可以绑定自定义dom事件吗?
> > ```
> >     <div
> >       ref={divRef}
> >       onSwipeup={setVisible(true)}
> >       className={cn("panel", { show: visible })}
> >     >
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会提示没有"onSwipeup"
> 
> 对的，不支持在 JSX 标签中直接写的，需要拿到 dom 然后用 JS 手动去绑。

好嘞,谢谢
