### ISSUE TITLE
[BUG] vue3 绑定@pan事件长按拖动松开后会触发多一次

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#80]

**Comment by 1014156094** [comment]
any-touch 1.0不存在这问题，2.0存在这问题

**Comment by any86** [comment]
> any-touch 1.0不存在这问题，2.0存在这问题

感谢, 我对比测测

**Comment by any86** [comment]
离开触点那下触发了pan,  这个是2.0我有意改动的,  可能和你的直觉不一样了,  这个我再找几个人看看大家的直觉是什么样的, 如果都觉得离开那下不应该, 我再改过来.

你也说下你的场景, 我也权衡下, 是不是我这么改动有问题.

其实离开触点的那次pan时间对应的deltaX/Y是等于0的, 而且距离和位移也都是和上一次的pan一摸一样的. 所以我觉得应该不会影响, 看来是影响1.0用户的代码了, 抱歉.

暂时可以你直觉的pan改成:
```javascript
at.on(['panstart','panmove'],e=>{

})
```

**Comment by 1014156094** [comment]
建议和原生的触发规律一样，这样大家能统一

**Comment by any86** [comment]
> 建议和原生的触发规律一样，这样大家能统一

好的, 但是原生指的是哪个? 安卓还是苹果, 其实1.0哪个应该是我当时的bug, 没有把panend算到pan里, 2.0我发现了, 就改过来了. 我其实不知道这个有规范的.

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/147580112-5b3d65ca-c8bb-4009-ad4c-0e630bfa4ac3.png)
我事件是参考hammer.js模仿的, 这是他的. 他就把panend算到pan里

**Comment by 1014156094** [comment]
> ![image](https://user-images.githubusercontent.com/8264787/147580112-5b3d65ca-c8bb-4009-ad4c-0e630bfa4ac3.png) 我事件是参考hammer.js模仿的, 这是他的. 他就把panend算到pan里

我懂了，@pan就是三合一了

**Comment by 1014156094** [comment]
那我用start和move吧

**Comment by any86** [comment]
好的, 我解决其他2个
