### ISSUE TITLE
[BUG] vue3 绑定@pan事件后，快速拖拽松开拖拽松开操作几次会@pan事件执行的函数会一直叠加

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#81]
比如我一下快速拖拽后松开重复这样的操作3次，下次拖拽10px的距离@pan事件就会一次触发3到4次了

**Comment by any86** [comment]
好的我检查下, 使用的版本是?

**Comment by any86** [comment]
提了3个issue, 都是同一个问题吧?  提供下vue版本和any-touch版本

**Comment by 1014156094** [comment]
> 提了3个issue, 都是同一个问题吧? 提供下vue版本和any-touch版本

不一样的问题，any-touch 2.0版本都存在这些问题

**Comment by any86** [comment]
好的, 我解决下

**Comment by any86** [comment]
你是如何确保拖拽了正好10px的呢?

**Comment by 1014156094** [comment]
> 你是如何确保拖拽了正好10px的呢?

10px是我假如的，总之会触发很多次就是了，你试下在移动端上一直短距离的拖拽松开就知道了

**Comment by any86** [comment]
移动端是真机吗? 我在谷歌模拟器上测试没有这个问题啊?  我是把我demo中swipe屏蔽了, 一直拖拽, 松开并没有出现拖拽错位, 也就是说没有多余的pan触发啊.
能再具体说下复现过程吗?

**Comment by 1014156094** [comment]
> 移动端是真机吗? 我在谷歌模拟器上测试没有这个问题啊? 我是把我demo中swipe屏蔽了, 一直拖拽, 松开并没有出现拖拽错位, 也就是说没有多余的pan触发啊. 能再具体说下复现过程吗?

控制台模拟器和真机都有这问题，这是我代码
```
import AT from "any-touch";

state.at = new AT(state.touchWrapDOM, {});
```

**Comment by any86** [comment]
1.0版本有吗?

**Comment by 1014156094** [comment]
> 1.0版本有吗?

有

**Comment by 1014156094** [comment]
没解决怎么就关闭了，还有我发现hammer.js也有这个bug，我自己用touchmove写是没问题的

**Comment by any86** [comment]
你在https://codesandbox.io/dashboard/home上复现下源码吧.
按照你说的用例, 我测试了, 没法复现bug
