### ISSUE TITLE
使用 pnpm install 安装的包无法按需引入

### ISSUE THREAD

**Issue by 1014156094** [any86/any-touch#82]
![image](https://user-images.githubusercontent.com/16074662/148325885-d93db7c1-204a-4592-9fd9-2e06fe9ffc5f.png)

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/148325900-4641e341-1bfd-4191-a502-6d5240cdc385.png) 没有"index". 删除试试

**Comment by 1014156094** [comment]
> ![image](https://user-images.githubusercontent.com/8264787/148325900-4641e341-1bfd-4191-a502-6d5240cdc385.png) 没有"index". 删除试试

一样不行的，node_modules 里面根本没有 @any-touch 目录
![image](https://user-images.githubusercontent.com/16074662/148325988-621cb089-56e8-4c95-bbd0-d76164dab509.png)

**Comment by any86** [comment]
在.pnpm中

**Comment by any86** [comment]
我想起来了, pnpm不让使用包的子包, 子包要设置成自己项目的依赖, 等我给你找下文档说明

**Comment by any86** [comment]
我看babe好像l解决了这个问题, 我研究下

**Comment by any86** [comment]
研究了一下午,  没找到有类似的项目, 文档也只是说从项目角度去解决, 暂时没办法, 先搁置吧. 
https://pnpm.io/zh/faq#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%881

如果非要用pnpm安装那就只能手动一个个安装了.
