### ISSUE TITLE
ios iphone上面的瀏覽器在scrolling的時候touch沒有反應

### ISSUE THREAD

**Issue by jason3120** [any86/any-touch#83]
即係當在html入面有一個長頁面，假設像ios apps一樣左上角有個menu button，但scrolling滾動時按這個button它沒有觸動touch的反應，這個情況只是在iphone的瀏覽器web browser上面發生，例如iphone上的safari和chrome都是一樣發生這個問題

**Comment by any86** [comment]
没有理解, 可以附上部分代码示意吗?

**Comment by jason3120** [comment]
> 没有理解, 可以附上部分代码示意吗?

Sorry，原來後尾我發覺一個ios的現象，在ios apps入面，為什麼scrolling的時候還可以按其他button，因為那個button有那個scroll view出面，而scrolling page入面的button還是按不到的

所以不是你的問題，如果要做到我的網頁效果，就要起碼分開兩個scroll view才可以做到，不能在同一個scroll view內

**Comment by any86** [comment]
ok
