### ISSUE TITLE
想咨询一下，事件绑定后需要手动销毁吗？

### ISSUE THREAD

**Issue by huyongdi** [any86/any-touch#85]
作者您好，通过on监听后，事件有销毁机制吗？还是需要手动怎么销毁一下？

**Comment by any86** [comment]
有的:
```javascript
at.on('tap', onTap);

// 取消
at.off('tap', onTap);

// 取消全部
at.off('tap');

// 销毁at
at.destroy();
```
文档漏了, 稍后我补上

**Comment by huyongdi** [comment]
> 有的:
> 
> ```js
> at.on('tap', onTap);
> 
> // 取消
> at.off('tap', onTap);
> 
> // 取消全部
> at.off('tap');
> 
> // 销毁at
> at.destroy();
> ```
> 
> 文档漏了, 稍后我补上

谢谢。顺便咨询一下。想做事件代理，比如把系统的所有事件都绑定在document下面，这种用on可以支持吗

**Comment by any86** [comment]
可以, 那就需要把at的第一个参数设置为`document`, 然后自己在on的回调中通过target去处理.

``` javascript
const at = new ATouch(document);
at.on('pan', e=>{
    e.target
})
```

**Comment by huyongdi** [comment]
> ```js
>  e.target
> ```

好的，感谢感谢，那估计就是我这边测试的时候，阻止了事件没代理到，我还以为不支持，这个我先关了，感谢大佬

**Comment by any86** [comment]
客气

**Comment by huyongdi** [comment]
> 有的:
> 
> ```js
> at.on('tap', onTap);
> 
> // 取消
> at.off('tap', onTap);
> 
> // 取消全部
> at.off('tap');
> 
> // 销毁at
> at.destroy();
> ```
> 
> 文档漏了, 稍后我补上



> 客气

我测试了一下。代码如下：
const at = new AnyTouch(document.body) // 没用document的原因是因为类型对不上
at.on('pan',e=>{
// 这里做打印
})
现象是：
document尝试拖动的时候可以打印，但是下面的子元素不行
我尝试用document.addEventListener('mousemove')这种测试，子元素拖动是可以捕获到的

**Comment by any86** [comment]
好的我试下

**Comment by any86** [comment]
```javascript
const at = new AnyTouch(document.body);
```
我把我的官方的demo就改了上面, 依然可以拖拽啊,   再多提供点代码信息, 我看下.

关于类型, `document`可以写成`document.documentElement`.
