### ISSUE TITLE
可以在canvas上使用吗？

### ISSUE THREAD

**Issue by Elon-Yan** [any86/any-touch#94]
可以在canvas上使用吗，用的是pixi引擎

**Comment by any86** [comment]
可以啊, at可以捕获在canvas元素上的所有手势,  但如果你指的是canvas内自己画的物体, 是没法直接捕获对应手势的, 这个就要进一步编程了.

**Comment by Elon-Yan** [comment]
关于“进一步编程”，不知道能否给个demo，我自已其实用pixi捣鼓了一段时间，都没能跑通。原本是使用[pixi-hammer](https://www.npmjs.com/package/pixi-hammer)的，但它太重了，想换成这个项目。

**Comment by any86** [comment]
我对这方面没研究, 帮不上忙啊, 我只是知道你要自己在canvas去判断触点是否在某个图形内, 比如isPontInPath这种api

**Comment by Elon-Yan** [comment]
恩恩，我理解是用catchEvent，然后在canvasElement.on('touchstart', (e) => {  })后，在函数里new Event()出来传进catchEvent里。
