### ISSUE TITLE
慢速拖动时 panend 有很大几率不触发

### ISSUE THREAD

**Issue by haydenull** [any86/any-touch#95]
非常棒的手势库，感谢开发者。
我这边的场景是拖动滑块，用户滑动距离不超过某个值时就松手时，让滑块复位。
我这边用 `isEnd` 判断是否松手。
测试发现慢速拖动时松手后捕捉不到 isEnd 为 true 的事件，专门监听了 panend 发现也没有触发。
官方示例可复现。
![2022-04-21 17 08 27](https://user-images.githubusercontent.com/17695989/164421939-629ef777-40f1-47c8-bbb7-6859087d28c9.gif)

**Comment by any86** [comment]
刚看到, 感谢反馈, 我研究下

**Comment by any86** [comment]
我试了并没有复现啊, 你是mac系统吗? mac下有可能会出现这个问题, 我身边暂时没有mac, 等我也再试试是不是下面这个问题

[macos 上的 chrome 浏览器触发 touchend 会比较慢](https://github.com/any86/any-touch/blob/master/docs/question.CN.md#macos-%E4%B8%8A%E7%9A%84-chrome-%E6%B5%8F%E8%A7%88%E5%99%A8%E8%A7%A6%E5%8F%91-touchend-%E4%BC%9A%E6%AF%94%E8%BE%83%E6%85%A2)

**Comment by any86** [comment]
我没有ios, 我用安卓也试了, 并没有问题啊, 我估计你移动的比较小, 所以被识别成press了, 这样pan就不会触发了. 可以通过单独引入pan解决
```javascript
import ATouch from '@any-touch/core '
import pan from '@any-touch/pan'
const at = new ATouch (el);
at.use(pan)
```

**Comment by haydenull** [comment]
我刚刚用windows chrome 也复现了，代码见[codesandbox](https://codesandbox.io/s/epic-stitch-ivqyy4?file=/src/App.js)

前三次拖动松手后都触发了 isEnd，第四层拖动较慢，松手后没有触发isEnd，所以滑块最后没有回到初始位置。

![动画](https://user-images.githubusercontent.com/17695989/164887976-30c05cdc-cb21-4f1f-8c2b-d8e6825d36c4.gif)

**Comment by any86** [comment]
我估计可能是pan触发需要一个"最小距离"的事, 参数叫"threshold", 默认是10px, 下面链接中第16行我改成了"threshold:0", 你再试试, 看看咱俩说的是不是以一个意思:
https://codesandbox.io/s/vibrant-swartz-ftb6s8?file=/src/App.js:443-452

**Comment by haydenull** [comment]
应该确实和这个参数有关系，设置上以后，isEnd 不触发的几率小了很多，但还是多来几次还是会出现

**Comment by any86** [comment]
一直没复现出来, 我留意下, 等我能复现了再修改,问题先挂着不关

**Comment by any86** [comment]
https://any86.github.io/any-touch/ 已解决, 请测试.  修复于any-touch@2.1.2

**Comment by Akimotorakiyu** [comment]
@any86 大佬，这个问题又有了，怎么搞。
chrome 设备切换到手机📱模式，太大概率不会触发 panend 了。

**Comment by any86** [comment]
@Akimotorakiyu  我尝试了复现, 并没有啊, 是安装的最新版本吗 2.2.0

https://any86.github.io/any-touch/#/

**Comment by Akimotorakiyu** [comment]
@any86 是啊，昨天刚新装的依赖

**Comment by any86** [comment]
@Akimotorakiyu 上面的网址是demo你看能复现问题吗?

**Comment by Akimotorakiyu** [comment]
@any86 抱歉，稍等，我刷下 npm 缓存看下

**Comment by Akimotorakiyu** [comment]
非常抱歉，打扰了，@any86 刷了缓存，好了，麻烦了

**Comment by any86** [comment]
@Akimotorakiyu 么事😊
