### ISSUE TITLE
[doc]  Add the library compatibility information?

### ISSUE THREAD

**Issue by wang1212** [any86/any-touch#96]
First of all, thank you very much for contributing such a good thing. 

However, when a library is used as a dependency in a **production** environment, **compatibility** issues are important. Have you considered adding relevant information to the documentation?

**Comment by any86** [comment]
编译器是是输出到es6代码, 其中也没用特别新的API, 因为我也不想兼容ie, 因为大部分情况下都是给移动端用, 所以我也没特意研究过兼容性, 浏览器兼容性有测试工具吗? 可以脚本执行那种?

**Comment by wang1212** [comment]
very sorry, I can't give you useful information about automated testing tools.

_However, the information that your code block compiles to **ES6** is also critical and I suggest you include it in the documentation, it might help a lot of people._

**Comment by any86** [comment]
3q, 我研究下相关测试工具
